packages:
  - packages/*
  - apps/*
  - infra/*

catalog:
  alchemy: ^0.92.2
  rimraf: 6.1.3
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - cbor-extract
  - cpu-features
  - esbuild
  - msgpackr-extract
  - protobufjs
  - ssh2
