packages:
  - packages/*
  - apps/*
  - infra/*

minimumReleaseAge: 4320
blockExoticSubdeps: true
trustPolicy: no-downgrade

catalog:
  alchemy: ^0.92.2
  rimraf: 6.1.3
  typescript: ^5.9.3

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  cbor-extract: true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  ssh2: true
  workerd: true
